Repository su-yeong-ice-pork/front-end, pull requests merged in 2025-02, with the labels that each got.

#56 [REFACTOR] HomeScreen api 연결
  package-lock.json
  package.json
  src/api/user/getUserDataType.ts
  src/components/Profile/ProfileHeader/index.tsx
  src/components/Profile/ProfileName/index.tsx
  src/components/Profile/index.tsx
  src/components/types/ProfileType/ProfileNameType.ts
  src/screens/HomeScreen/index.tsx
Labels: 🛠️refactor

#58 [REFACTOR] 회원가입 api 연결
  src/api/checkEmail.ts
  src/api/signUp/email.ts
  src/api/signUp/name.ts
  src/api/signUp/signUp.ts
  src/api/signUp/types.ts
  src/api/signup.ts
  src/components/SignUp/InputPassword/index.tsx
  src/components/SignUp/NickName/index.tsx
  src/components/SignUp/RegisterDepart/RegisterModal/index.tsx
  src/components/SignUp/SaveButton/index.tsx
  src/components/SignUp/VerifyEmail/InputBox/index.tsx
  src/components/SignUp/VerifyEmail/VerifyCode/index.tsx
  src/components/SignUp/VerifyEmail/index.tsx
  src/components/types/SignUpType/VerifyEmail.ts
  src/hooks/useCheckName.ts
  src/hooks/useSignUp.ts
  src/hooks/useVerifyEmail.ts
  src/recoil/signUpAtom.ts
  src/screens/SignUpScreen/index.tsx
  src/utils/FormatTime.ts
Labels: 🛠️refactor

#61 [REFACTOR] FindPasswordScreen API 연결 및 구조 개선
  src/api/resetPassword.ts
  src/api/resetPassword/checkPasswordEmail.ts
  src/api/resetPassword/resetPassword.ts
  src/api/resetPassword/types.ts
  src/hooks/useFindPassword.ts
  src/screens/FindPasswordScreen/index.tsx
Labels: 🛠️refactor

#65 [REFACTOR] Streak API 연결 및 구조 개선
  src/api/record/getRecordDataApi.ts
  src/api/record/getRecordDataType.ts
  src/components/Calendars/Daycount/index.tsx
  src/components/Calendars/MonthCalendar/index.tsx
  src/components/Calendars/StudyStats/index.tsx
  src/hooks/calendar/useRecord.ts
  src/recoil/recordAtom.ts
  src/screens/HomeScreen/index.tsx
Labels: 🛠️refactor

#51 [🛠️refactor] ProfileScreen 구조 개선
  App.tsx
  components/ui/index.ts
  src/api/badge/getBadgesPropsType.ts
  src/components/Badges/BadgeText/HomeBadgeTextStyles.ts
  src/components/Badges/BadgeText/ProfileBadgeTextStyles.ts
  src/components/Badges/BadgeText/index.tsx
  src/components/Badges/BadgeView/HomeBadgeViewStyles.ts
  src/components/Badges/BadgeView/ProfileBadgeViewStyles.ts
  src/components/Badges/BadgeView/index.tsx
  src/components/Badges/HomeBadgeStyles.ts
  src/components/Badges/ProfileBadgeStyles.ts
  src/components/Badges/index.tsx
  src/components/Freeze/FreezeInfo/freezeInfoStyles.ts
  src/components/GrassCard/GrassCardStyle.ts
  src/components/GrassCard/GrassInfoCard/GrassInfoCardStyles.ts
  src/components/GrassCard/GrassInfoCard/index.tsx
  src/components/GrassCard/GrassTitle/GrassTitleStyles.ts
  src/components/GrassCard/GrassTitle/index.tsx
  src/components/GrassCard/index.tsx
  src/components/ListViewBox/ListViewBoxStyels.ts
  src/components/ListViewBox/index.tsx
  src/components/Modal/LogoutModal.tsx
  src/components/Modal/LogoutModalStyle.ts
  src/components/ProfileAction/ProfileActionButton/ProfileActionButtonStyle.ts
  src/components/ProfileAction/ProfileActionButton/index.tsx
  src/components/ProfileAction/ProfileActionStyle.ts
  src/components/ProfileAction/index.tsx
  src/components/types/GrassCardType/GrassCardType.ts
  src/components/types/ListViewBoxType/ListViewBoxType.ts
  src/components/types/ModalType/LogoutModalProps.ts
  src/components/types/ProfileType/ProfileType.ts
  src/constants/GrassCard/FontSizes.ts
  src/constants/GrassCard/GrassCardAltMessage.ts
  src/constants/Profile/GrassCard.ts
  src/constants/Profile/LogoutModal.ts
  src/constants/Profile/Profile.ts
  src/constants/Profile/ProfileAction.ts
  src/screens/FriendsProfileScreen/index.tsx
  src/screens/HomeScreen/index.tsx
  src/screens/ProfileScreen.tsx
  src/screens/ProfileScreen/ProfileScreenStyle.ts
  src/screens/ProfileScreen/index.tsx
Labels: 🛠️refactor

#64 [FEATURE] 스터디 방 생성하기 화면 구현
  App.tsx
  assets/images/icons/clockRed.png
  assets/images/icons/creatingIcon.png
  assets/images/illustration/createStudy.png
  components/ui/gluestack-ui-provider/config.ts
  src/components/BottomBar/BottomBarButton/BottomBarButtonStyles.ts
  src/components/BottomBar/BottomBarImage/BottomBarImage.ts
  src/components/CreateStudyForm/CreateStudyFormStyles.ts
  src/components/CreateStudyForm/InputField/InputFieldStyles.ts
  src/components/CreateStudyForm/InputField/index.tsx
  src/components/CreateStudyForm/Introduction/IntroductionStyles.ts
  src/components/CreateStudyForm/Introduction/index.tsx
  src/components/CreateStudyForm/SubmitButton/SubmitButtonStyles.ts
  src/components/CreateStudyForm/SubmitButton/index.tsx
  src/components/CreateStudyForm/index.tsx
  src/components/StudyGroupSection/CreateStudyButton/CreateStudyButtonStyles.ts
  src/components/StudyGroupSection/CreateStudyButton/index.tsx
  src/components/StudyGroupSection/StudyGroupSectionStyles.ts
  src/components/StudyGroupSection/StudyList/StudyItem/StudyItemStyles.ts
  src/components/StudyGroupSection/StudyList/StudyListStyles.ts
  src/components/StudyGroupSection/StudyList/index.tsx
  src/components/StudyGroupSection/index.tsx
  src/components/types/CreateScreenType/InputFieldType.ts
  src/components/types/CreateScreenType/SubmitButtonType.ts
  src/components/types/NavigationType/NavigationType.ts
  src/constants/BottomBar/Images.ts
  src/constants/CreateStudy/createStudy.ts
  src/constants/image/icons.ts
  src/constants/image/illustrations.ts
  src/constants/styles/color/color.ts
  src/screens/CreateStudyScreen/CreateStudyScreenStyles.ts
  src/screens/CreateStudyScreen/index.tsx
  src/screens/StudyScreen/StudyScreenStyles.ts
  src/screens/StudyScreen/index.tsx
Labels: 🚀 feature

#66 [REFACTOR] StudyScreen API 연결 및 구조 개선
  App.tsx
  src/api/study/studies/studies.ts
  src/api/study/studyDetail/studyDetail.ts
  src/api/study/studyDetail/studyParticipants.ts
  src/api/study/types.ts
  src/api/user/getUserDataType.ts
  src/components/Profile/ProfileHeader/index.tsx
  src/components/Profile/ProfileName/index.tsx
  src/components/StudyDetail/StudyDetailHeader/index.tsx
  src/components/StudyDetail/StudyMemberList/StudyMember/index.tsx
  src/components/StudyDetail/StudyMemberList/index.tsx
  src/components/StudyGroupSection/RandomStudyGroupSection/index.tsx
  src/components/StudyGroupSection/RandomStudyHeader/RandomStudyHeaderStyles.ts
  src/components/StudyGroupSection/RandomStudyHeader/index.tsx
  src/components/StudyGroupSection/StudyList/StudyItem/index.tsx
  src/components/StudyGroupSection/StudyList/index.tsx
  src/components/types/StudyDetailType/StudyDetailType.ts
  src/components/types/StudyGroupScreenType/StudyGroupDataType.ts
  src/components/types/StudyGroupScreenType/StudyItemProps.ts
  src/constants/StudyDetail/studyDetail.ts
  src/hooks/useStudies.ts
  src/hooks/useStudyDetail.ts
  src/hooks/useStudyParticipants.ts
  src/screens/HomeScreen/index.tsx
  src/screens/ProfileScreen/index.tsx
  src/screens/StudyDetailScreen/index.tsx
  src/screens/StudyScreen/index.tsx
Labels: 🛠️refactor

#71 [FEATURE] RankingSection 구현
  assets/images/icons/friendsIconColored.png
  src/components/StudyRecord/RankingSection/ChoiceRankingButton/ChoiceRankingButtonStyles.ts
  src/components/StudyRecord/RankingSection/ChoiceRankingButton/index.tsx
  src/components/StudyRecord/RankingSection/RankingList/GroupRankingList/index.tsx
  src/components/StudyRecord/RankingSection/RankingList/IndividualRankingList/index.tsx
  src/components/StudyRecord/RankingSection/RankingList/RankingListStyles.ts
  src/components/StudyRecord/RankingSection/RankingSectionStyles.ts
  src/components/StudyRecord/RankingSection/index.tsx
  src/components/types/RankingType/RankingButtonType.ts
  src/constants/Ranking/Dummy/GroupRankingList.ts
  src/constants/Ranking/Dummy/IndividualRankingList.ts
  src/constants/Ranking/Ranking.ts
  src/constants/image/icons.ts
Labels: 🚀 feature

#72 [FEATURE] 스터디 방 생성 API 구현
  src/api/study/studies/createStudy.ts
  src/api/study/types.ts
  src/components/CreateStudyForm/index.tsx
  src/components/Profile/ProfileName/index.tsx
  src/components/types/StudyDetailType/StudyDetailType.ts
  src/hooks/useCreateStudy.ts
  src/hooks/useCreateStudyForm.ts
  src/screens/StudyDetailScreen/index.tsx
Labels: 🚀 feature

#73 [REFACTOR] Jandi API 연결
  package-lock.json
  package.json
  src/api/monthGrass/getMonthGrassAPI.ts
  src/api/monthGrass/getMonthGrassType.ts
  src/api/yearGrass/getYearGrassAPI.ts
  src/api/yearGrass/getYearGrassType.ts
  src/components/Calendars/MonthCalendar/CalendarTabs.tsx
  src/components/Calendars/MonthCalendar/CustomCalendar.tsx
  src/components/Calendars/MonthCalendar/index.tsx
  src/components/Calendars/YearCalendar/CalendarGrid.tsx
  src/components/Calendars/YearCalendar/CalendarLables.tsx
  src/components/Calendars/YearCalendar/index.tsx
  src/hooks/calendar/useCalendarDates.ts
  src/hooks/calendar/useMonthGrass.ts
  src/hooks/calendar/useYearGrass.ts
  src/recoil/monthGrassAtom.ts
  src/recoil/yearGrassAtom.ts
  src/screens/HomeScreen/index.tsx
  src/utils/calendarUtils.ts
  src/utils/grassUtils.ts
Labels: bug, 🛠️refactor

#77 [Feature] 기록 랭킹 API 구현
  src/api/rankings/individual.ts
  src/api/rankings/studies.ts
  src/api/rankings/types.ts
  src/components/StudyRecord/RankingSection/RankingList/GroupRankingList/index.tsx
  src/components/StudyRecord/RankingSection/RankingList/IndividualRankingList/index.tsx
  src/components/StudyRecord/RankingSection/index.tsx
  src/components/types/RankingType/RankingSectionType.ts
  src/hooks/rankings/useGroupRanking.ts
  src/hooks/rankings/useIndividualRanking.ts
  src/hooks/rankings/useRankingSection.ts
Labels: 🚀 feature

#80 [Feature] 친구 프로필 api 구현
  src/api/friends/getFriendsAPI.ts
  src/api/friends/getFriendsTypes.ts
  src/components/StudyRecord/RecordTapSection/FriendsList/index.tsx
  src/hooks/useFriends.ts
  src/screens/HomeScreen/index.tsx
Labels: 🚀 feature
